name: CICD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Build step
        run: echo "Building project..."

  test:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Python
        run: python3 --version

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt || true
          pip3 install pytest pytest-cov coverage

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml:coverage.xml

      - name: Verify coverage file
        run: |
          ls -la
          cat coverage.xml | head -n 20

      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  sonar:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Verify coverage file
        run: |
          ls -la
          cat coverage.xml | head -n 20

      - name: SonarQube Scan
        run: |
          docker run --rm \
            -v $(pwd):/usr/src \
            -w /usr/src \
            sonarsource/sonar-scanner-cli \
            sonar-scanner \
            -Dsonar.projectKey=sumit_github_cicd \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Check Quality Gate
        run: |
          echo "Checking SonarQube Quality Gate..."

          for i in {1..12}; do
            STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=sumit_github_cicd" \
            | python3 -c "import sys, json; print(json.load(sys.stdin)['projectStatus']['status'])")

            echo "Quality Gate Status: $STATUS"

            if [ "$STATUS" = "OK" ]; then
              echo "Quality Gate PASSED"
              exit 0
            fi

            if [ "$STATUS" = "ERROR" ]; then
              echo "Quality Gate FAILED"
              exit 1
            fi

            echo "Waiting for analysis..."
            sleep 5
          done

          echo "Timeout waiting for Quality Gate"
          exit 1

  deploy:
    needs: sonar
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run container
        run: |
          docker stop my-app || true
          docker rm my-app || true
          docker build -t my-app .
          docker run -d -p 5000:5000 --name my-app my-app
