name: CICD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Build step
        run: echo "Building project..."

  test:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Python
        run: python3 --version

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt || true
          pip3 install pytest pytest-cov coverage

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml

  sonar:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        run: |
          docker run --rm \
            -v $(pwd):/usr/src \
            sonarsource/sonar-scanner-cli \
            sonar-scanner \
            -Dsonar.projectKey=sumit_github_cicd \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Check Quality Gate
        run: |
          STATUS="PENDING"

          while [ "$STATUS" = "PENDING" ]; do
            sleep 5
            STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=sumit_github_cicd" \
            | grep -o '"status":"[^"]*"' | cut -d'"' -f4)
            echo "Quality Gate Status: $STATUS"
          done

          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed"
            exit 1
          fi

  deploy:
    needs: sonar
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run container
        run: |
          docker stop my-app || true
          docker rm my-app || true
          docker build -t my-app .
          docker run -d -p 5000:5000 --name my-app my-app
